substitutions:
  project_branch: master
  project_version: 2025-master
  project_source: github://allexashka/esphome-termostat-master@$project_branch
  project_source_refresh: 12h
  node_name: "#"
  friendly_name: $node_name
  node_add_mac_suffix: "false"

esphome:
  name: $node_name
  friendly_name: $friendly_name
  name_add_mac_suffix: $node_add_mac_suffix
  comment: https://t.me/dentra_blog
  project:
    name: "dentra.ewh-$framework_type-$board"
    version: "$project_version"
  min_version: "2024.12.4"

preferences:
  flash_write_interval: 10min

wifi:
  ap:
captive_portal:

ota:
  - platform: esphome

logger:
  baud_rate: 0

external_components:
  - source: $project_source
    components: [rka_api, ets]   # ← добавлен ets
    refresh: $project_source_refresh