substitutions:
  project_branch: master
  project_version: 2025-master
  node_name: "#"
  friendly_name: $node_name
  node_add_mac_suffix: "false"

esphome:
  name: $node_name
  friendly_name: $friendly_name
  name_add_mac_suffix: $node_add_mac_suffix
  comment: https://t.me/dentra_blog
  project:
    name: "dentra.ewh-$framework_type-$board"
    version: "$project_version"
  min_version: "2024.12.4"

preferences:
  flash_write_interval: 10min

wifi:
  ap:

captive_portal:

ota:
  - platform: esphome

logger:
  baud_rate: 0

external_components:
  # 1. Базовые компоненты от dentra (vport обязателен)
  - source: github://dentra/esphome-components@master
    components: [crash_info, etl, otax, vport]
    refresh: 1d

  # 2. Ваши локальные компоненты (rka_api и ets)
  # Путь относительно корня конфигурации ESPHome
  - source:
      type: local
      path: packages/ets_termostat/components
    components: [rka_api, ets]