substitutions:
  board: esp32-c3-devkitm-1
  framework_type: esp-idf

esphome:
  platformio_options:
    build_flags:
      - -std=gnu++17
    build_unflags:
      - -std=gnu++11
    lib_ldf_mode: "chain"

esp32:
  board: $board
  framework:
    type: $framework_type
